services:
  - type: web
    name: music-backend
    env: node
    rootDir: server
    buildCommand: pip install -U yt-dlp && npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
